# Welcome to Jekyll!
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale: "en-US"
title: "Jiee Zhong"
title_separator: "-"
name: &name "Jiee Zhong"
description: &description "Assistant Professor at Miami University"
url: https://jieezhong.github.io
baseurl: "" # the subpath of your site, e.g. "/blog"
repository: "jieezhong/jieezhong.github.io"
teaser: "" # filename of teaser fallback teaser image placed in /images/, e.g., "500x300.png"
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# Comments
comments:
  provider: false

staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "master" # or "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"

# Social Sharing
twitter:
  username: ZhongJiee

# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id:

# Site Author
author:
  name: "Jiee Zhong"
  avatar: "Jiee_headshot.jpg"
  bio: "Assistant Professor of Economics"
  location: "Miami University"
  email: "jieezhong@gmail.com"
  linkedin: "jieezhong"
  twitter: "@ZhongJiee"

# Reading Files
include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - .bundle
  - .jekyll-assets-cache
  - node_modules

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development